### ISSUE TITLE
facebook photo doesn't work any more

### ISSUE THREAD

**Issue by thomalexandre** [thomalexandre/qking4u#4]

**Comment by Szeki** [comment]
So I hope I fixed it. There were (at least) two problems: 1. there was a breaking change in show_avatar.html.twig; the connection to facebook's graph api wasn't closed automatcally

**Comment by Szeki** [comment]
Still there is some issue with this. For me, sometimes it works and I can get the profile pic in seconds, sometimes in 10 seconds, sometimes I could wait for hours still nothing happen. I don't know that the problem is with local webserver, or there is a bigger issue.

**Comment by Szeki** [comment]
Currently we use php's file_get_contents, which as I understood most of the time disabled on hosts. I tried to curl with no success, the problem is that the graph api redirects to an url but when I want to get the image from this url there is no return value.
I will try to add Facebook PHP SDK to the project. As it official, hopefully it could work and it is fast...

**Comment by Szeki** [comment]
https://github.com/facebook/facebook-php-sdk-v4

**Comment by thomalexandre** [comment]
![screenshot 2015-03-04 16 14 05](https://cloud.githubusercontent.com/assets/1586244/6486197/87367ce8-c289-11e4-9446-046d98e60fab.png)

**Comment by Szeki** [comment]
Please check it now. There was problem if you're using PHP 5.6 (need to set some extra options).

**Comment by thomalexandre** [comment]
I got the alert error

**Comment by Szeki** [comment]
the same error?

**Comment by Szeki** [comment]
try to go users/edit/update_fb_picture/. What's the error message on that?

**Comment by Szeki** [comment]
Please try again. I changed the picture root to upload from UploadDir to UploadRootDir
